version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    command: tail -f /dev/null
    container_name: hints_dev_container
    restart: unless-stopped
